### ISSUE TITLE
Properties

### ISSUE THREAD

**Issue by deamme** [twfarland/kilroy#1]
How do I access node properties quickly like when accessing attributes? When accessing attributes I just define an object - what do I do with properties?

**Comment by twfarland** [comment]
Hi, I'm not sure I understand the question.
By node, do you mean dom node? Kilroy doesn't have any facilities for working with the dom directly.
In an event handler, the parameter represents the 'context', which has `.el` (the underlying dom node) and `.event` (the underlying dom event) properties. In the handler, `this` represents the instance of the Kilroy component.

**Comment by deamme** [comment]
I just wanted to style the elements but I guess I can just do that with the style attribute..

**Comment by twfarland** [comment]
That's the way. The point of this library is that you should never need to modify the dom directly.

**Comment by deamme** [comment]
I see, thank you!
